"""Add time fields to Participant model

Revision ID: 1eaff82ec127
Revises: 9f4d00277354
Create Date: 2024-06-12 16:14:29.788541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eaff82ec127'
down_revision = '9f4d00277354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time3', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time4', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('time5', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('time5')
        batch_op.drop_column('time4')
        batch_op.drop_column('time3')
        batch_op.drop_column('time2')
        batch_op.drop_column('time1')

    # ### end Alembic commands ###
